# Random Syslog-formatted logs
[sources.dummy_logs]
type = "demo_logs"
format = "syslog"
interval = 1.0

# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev
[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
'''

[sinks.cloki_syslog]
type="loki"
inputs = ["parse_logs"]
endpoint = "http://qryn:3100/loki/api/v1/push"
tenant_id = "0"
compression = "none"

    [sinks.cloki_syslog.labels]
    forwarder = "vector"
    event = "{{ facility }}"
    type = "syslog"

    [sinks.cloki_syslog.encoding]
    codec = "json"
