version: '3.1'

volumes:
    grafana_data: {}
    clickhouse_data: {}

services:
  grafana:
    image: grafana/grafana:master
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXPLORE_ENABLED=true
      - GF_INSTALL_PLUGINS="vertamedia-clickhouse-datasource"
      - GF_ALERTING_ENABLED=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS="vertamedia-clickhouse-datasource"
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      - clickhouse-server

  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/metric_log.xml:/etc/clickhouse-server/config.d/metric_log.xml
      - ./docker/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    ports:
      - 8123:8123
      - 9000:9000
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30

  qryn:
    image: qxip/qryn:latest
    container_name: qryn
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse-server
      - DEBUG=true
    depends_on:
      - clickhouse-server

  pastash:
    image: qxip/pastash-loki
    container_name: pastash
    volumes:
      - ./pastash/pastash.json:/config/loki.conf
      - /var/log:/var/log:ro
    depends_on:
      - qryn
      
  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml
    depends_on:
      - qryn
