# config file version
apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: true
- name: Tempo
  type: tempo
  access: proxy
  url: http://loki:3100
  editable: true
